# Generated by Django 5.0.2 on 2024-02-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbyname_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hobbyname', models.TextField(max_length=20)),
            ],
        ),
    ]
