# Generated by Django 5.0.2 on 2024-02-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0003_hobbyfactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season_name', models.TextField(max_length=20)),
            ],
        ),
    ]
