# Generated by Django 5.0.2 on 2024-02-29 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0005_seasonfactor_tb'),
        ('user', '0010_customerhobby_factor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season_country_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.IntegerField()),
                ('Country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country_tb')),
                ('Season_factor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.seasonfactor_tb')),
                ('Season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.season_tb')),
                ('State_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.state_tb')),
            ],
        ),
    ]
