# Generated by Django 5.0.2 on 2024-02-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0006_season_country_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agefactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Minimum_age', models.IntegerField()),
                ('Maximum_age', models.IntegerField()),
                ('Factor_name', models.CharField(max_length=200)),
            ],
        ),
    ]
