# Generated by Django 5.0.2 on 2024-02-27 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_name', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_name', models.TextField(max_length=20)),
                ('Country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country_tb')),
            ],
        ),
    ]
