# Generated by Django 5.0.2 on 2024-02-27 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=20)),
                ('Gender', models.TextField(max_length=20)),
                ('DOB', models.TextField(max_length=20)),
                ('Address', models.TextField(max_length=20)),
                ('Phone', models.TextField(max_length=20)),
                ('Security_question', models.TextField(max_length=20)),
                ('Answer', models.TextField(max_length=20)),
                ('Username', models.TextField(max_length=20)),
                ('Password', models.TextField(max_length=20)),
                ('Country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country_tb')),
                ('State_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.state_tb')),
            ],
        ),
    ]
