# Generated by Django 5.0.2 on 2024-02-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0005_seasonfactor_tb'),
        ('user', '0002_register_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hobby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.hobbyname_tb')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.register_tb')),
            ],
        ),
    ]
