# Generated by Django 5.0.2 on 2024-02-27 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_hobby_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.TextField(max_length=20)),
                ('Message', models.TextField(max_length=20)),
                ('Date', models.TextField(max_length=20)),
                ('Time', models.TextField(max_length=20)),
                ('Status', models.TextField(max_length=20)),
                ('Filterstatus', models.TextField(max_length=20)),
                ('Reciever_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever_id', to='user.register_tb')),
                ('Sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='user.register_tb')),
            ],
        ),
    ]
