# Generated by Django 5.0.2 on 2024-02-27 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_message_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.TextField(max_length=20)),
                ('Time', models.TextField(max_length=20)),
                ('Message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.message_tb')),
                ('Reciever_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever_Id', to='user.message_tb')),
            ],
        ),
    ]
