# Generated by Django 5.0.2 on 2024-02-28 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_contact_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocklist_tn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=20)),
                ('Date', models.TextField(max_length=20)),
                ('Time', models.TextField(max_length=20)),
                ('Remark', models.TextField(max_length=20)),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_Id', to='user.register_tb')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Id', to='user.register_tb')),
            ],
        ),
    ]
