# Generated by Django 5.0.2 on 2024-02-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_blocklist_tn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blocklist_tn',
            new_name='Blocklist_tb',
        ),
    ]
