# Generated by Django 5.0.2 on 2024-02-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0005_seasonfactor_tb'),
        ('user', '0009_rename_blocklist_tn_blocklist_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerhobby_factor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Factor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.hobbyfactor_tb')),
                ('Hobby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.hobbyname_tb')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ID', to='user.register_tb')),
            ],
        ),
    ]
