# Generated by Django 5.0.2 on 2024-02-29 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0007_agefactor_tb'),
        ('user', '0010_customerhobby_factor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_agefactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agefactor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.agefactor_tb')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_iD', to='user.register_tb')),
            ],
        ),
    ]
