# Generated by Django 5.0.2 on 2024-03-01 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0007_agefactor_tb'),
        ('user', '0011_customer_agefactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerseason_factor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Factor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.seasonfactor_tb')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.register_tb')),
            ],
        ),
    ]
